//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gsb_desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelGSB : DbContext
    {
        public ModelGSB()
            : base("name=ModelGSB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<laboratoire> laboratoire { get; set; }
        public virtual DbSet<secteur> secteur { get; set; }
        public virtual DbSet<travailler> travailler { get; set; }
        public virtual DbSet<visiteur> visiteur { get; set; }
    }
}
